- name: Deploy Java App
  hosts: localhost
  tasks:
    - name: Apply Kubernetes manifests
      command: kubectl apply -f {{ item }}
      with_items:
        - k8s-manifests/java-app-deployment.yaml
        - k8s-manifests/java-app-service.yaml
        # - k8s-manifests/ingress.yaml
        - k8s-manifests/hpa.yaml
