- name: Deploy Java App
  hosts: localhost
  tasks:
    - name: Apply Kubernetes manifests
      command: kubectl apply -f {{ item }}
      with_items:
        - yaml/java-app-deployment.yaml
        - yaml/java-app-service.yaml
        - yaml/ingress.yaml
        - yaml/hpa.yaml