apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dream-cluster
  region: us-east-1

availabilityZones:
  - us-east-1a
  - us-east-1b
  - us-east-1c

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 2
    ssh:
      allow: true
      publicKeyName: dream_key_pair