apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dream-cluster
  region: us-east-1

nodeGroups:
  - name: ng-2
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    ssh:
      allow: true
      publicKeyName: dream_key_pair